# Generated by Django 4.2.5 on 2023-11-28 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notareclamo',
            name='orden_compra',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
        migrations.DeleteModel(
            name='NotaReclamo',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
